// apps/web/app/page.tsx
"use client";
import {
  useOrgaAI,
  OrgaVideo,
  OrgaAudio,
  ORGAAI_MODELS,
  ORGAAI_TEMPERATURE_RANGE,
  ORGAAI_VOICES,
  OrgaAIModel,
  OrgaAIVoice,
  ConnectionState,
  ConversationItem
} from "@orga-ai/react";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Button } from "@/components/ui/button";
import {
  Mic,
  MicOff,
  Video,
  CameraOffIcon,
  Settings,
  X,
  ChevronDown,
  ChevronUp,
  MessageSquare,
} from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Textarea } from "@/components/ui/textarea";

export default function Home() {
  const {
    startSession,
    endSession,
    userVideoStream,
    aiAudioStream,
    connectionState,
    isCameraOn,
    isMicOn,
    toggleCamera,
    toggleMic,
    model,
    voice,
    temperature,
    conversationItems,
    updateParams,
  } = useOrgaAI();
  const [instructionsText, setInstructionsText] = useState("");
  const [isConfigOpen, setIsConfigOpen] = useState(false);
  const [instructionsUpdated, setInstructionsUpdated] = useState(false);
  const [isConversationOpen, setIsConversationOpen] = useState(false);
  const conversationRef = useRef<HTMLDivElement>(null);

  const buttonText = () => {
    if (connectionState === "connected") {
      return "Disconnect";
    } else if (connectionState === "connecting") {
      return "Connecting...";
    } else {
      return "Connect";
    }
  };

  const isConnected = connectionState === "connected";

  // Close conversation panel when disconnecting
  useEffect(() => {
    if (!isConnected) {
      setIsConversationOpen(false);
    }
  }, [isConnected]);

  // Auto-scroll to bottom when new messages arrive
  useEffect(() => {
    if (conversationRef.current) {
      conversationRef.current.scrollTop = conversationRef.current.scrollHeight;
    }
  }, [conversationItems]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 p-4">
      <div className="max-w-7xl mx-auto h-[calc(100vh-2rem)] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-3xl font-bold text-slate-900">
              OrgaAI Playground
            </h1>
            <p className="text-slate-600 mt-1">
              Test and explore the OrgaAI SDK
            </p>
          </div>

          {/* Connection Status */}
          <div className="flex items-center gap-3">
            <div
              className={`px-3 py-1 rounded-full text-sm font-medium ${
                isConnected
                  ? "bg-green-100 text-green-800"
                  : "bg-slate-100 text-slate-600"
              }`}
            >
              {connectionState === "connected" ? "Connected" : "Disconnected"}
            </div>

            {/* Config and Conversation Toggle Buttons */}
            {isConnected && (
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setIsConfigOpen(!isConfigOpen)}
                  className="flex items-center gap-2"
                >
                  <Settings className="w-4 h-4" />
                  Config
                  {isConfigOpen ? (
                    <ChevronUp className="w-4 h-4" />
                  ) : (
                    <ChevronDown className="w-4 h-4" />
                  )}
                </Button>

                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setIsConversationOpen(!isConversationOpen)}
                  className="flex items-center gap-2"
                >
                  <MessageSquare className="w-4 h-4" />
                  Conversation
                  {isConversationOpen ? (
                    <ChevronUp className="w-4 h-4" />
                  ) : (
                    <ChevronDown className="w-4 h-4" />
                  )}
                </Button>
              </div>
            )}
          </div>
        </div>

        {/* Main Content */}
        <div className="flex-1 flex gap-6">
          {/* Camera Preview - Centered */}
          <div className="flex-1 flex items-center justify-center">
            <div className="relative w-full max-w-2xl aspect-video bg-white rounded-2xl shadow-lg overflow-hidden border border-slate-200">
              {/* Camera Preview */}
              <div className="relative w-full h-full flex items-center justify-center bg-gradient-to-br from-slate-100 to-slate-200">
                {isCameraOn && userVideoStream ? (
                  <OrgaVideo
                    stream={userVideoStream}
                    className="w-full h-full object-cover"
                  />
                ) : (
                  <div className="text-center">
                    <div className="w-24 h-24 mx-auto mb-4 rounded-full bg-slate-300 flex items-center justify-center">
                      <CameraOffIcon className="w-12 h-12 text-slate-500" />
                    </div>
                    <p className="text-slate-600 font-medium">Camera Preview</p>
                    <p className="text-slate-500 text-sm mt-1">
                      {isCameraOn ? "Camera is on" : "Camera is off"}
                    </p>
                  </div>
                )}
              </div>

              {/* Connection Status Overlay */}
              {!isConnected && (
                <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
                  <div className="text-center text-white">
                    <p className="text-lg font-medium mb-2">Not Connected</p>
                    <p className="text-sm opacity-90">
                      Connect to start using the camera
                    </p>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Configuration Panel */}
          {isConnected && isConfigOpen && (
            <div className="w-96 bg-white rounded-xl shadow-lg border border-slate-200 p-6 overflow-y-auto">
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-xl font-semibold text-slate-900">
                  Model Configuration
                </h2>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setIsConfigOpen(false)}
                >
                  <X className="w-4 h-4" />
                </Button>
              </div>

              <div className="space-y-6">
                {/* Model Selection */}
                <div className="space-y-2">
                  <Label className="text-sm font-medium text-slate-700">
                    Model
                  </Label>
                  <Select
                    value={model}
                    onValueChange={(value) =>
                      updateParams({ model: value as OrgaAIModel })
                    }
                  >
                    <SelectTrigger className="w-full">
                      <SelectValue placeholder="Select a model" />
                    </SelectTrigger>
                    <SelectContent>
                      {ORGAAI_MODELS.map((model) => (
                        <SelectItem key={model} value={model}>
                          {model}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                {/* Voice Selection */}
                <div className="space-y-2">
                  <Label className="text-sm font-medium text-slate-700">
                    Voice
                  </Label>
                  <Select
                    value={voice}
                    onValueChange={(value) =>
                      updateParams({ voice: value as OrgaAIVoice })
                    }
                  >
                    <SelectTrigger className="w-full">
                      <SelectValue placeholder="Select a voice" />
                    </SelectTrigger>
                    <SelectContent>
                      {ORGAAI_VOICES.map((voice) => (
                        <SelectItem key={voice} value={voice}>
                          {voice}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                {/* Temperature Slider */}
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <Label className="text-sm font-medium text-slate-700">
                      Temperature
                    </Label>
                    <span className="text-sm text-slate-500">
                      {temperature?.toFixed(1)}
                    </span>
                  </div>
                  <Slider
                    value={temperature ? [temperature] : [0]}
                    onValueChange={(value) =>
                      updateParams({ temperature: value[0] })
                    }
                    min={ORGAAI_TEMPERATURE_RANGE.min}
                    max={ORGAAI_TEMPERATURE_RANGE.max}
                    step={0.1}
                    className="w-full"
                  />
                  <div className="flex justify-between text-xs text-slate-500">
                    <span>{ORGAAI_TEMPERATURE_RANGE.min}</span>
                    <span>{ORGAAI_TEMPERATURE_RANGE.max}</span>
                  </div>
                </div>

                {/* Instructions */}
                <div className="space-y-2">
                  <Label className="text-sm font-medium text-slate-700">
                    Instructions
                  </Label>
                  <Textarea
                    value={instructionsText}
                    onChange={(e) => {
                      setInstructionsText(e.target.value);
                      setInstructionsUpdated(false);
                    }}
                    placeholder="Enter custom instructions for the AI..."
                    className="min-h-[100px] resize-none"
                  />
                  <div className="flex items-center gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => {
                        updateParams({ instructions: instructionsText });
                        setInstructionsUpdated(true);
                        // Reset the success state after 3 seconds
                        setTimeout(() => setInstructionsUpdated(false), 3000);
                      }}
                      className="flex-1"
                    >
                      Update Instructions
                    </Button>
                    {instructionsUpdated && (
                      <div className="flex items-center gap-1 text-green-600 text-sm">
                        <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
                        Updated!
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Conversation Panel */}
          {isConnected && isConversationOpen && (
            <div className="w-96 bg-white rounded-xl shadow-lg border border-slate-200 flex flex-col h-[600px]">
              <div className="flex items-center justify-between p-6 border-b border-slate-200 flex-shrink-0">
                <div>
                  <h2 className="text-xl font-semibold text-slate-900">
                    Conversation
                  </h2>
                  <p className="text-xs text-slate-500 mt-1">
                    Real-time conversation items from SDK
                  </p>
                </div>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setIsConversationOpen(false)}
                >
                  <X className="w-4 h-4" />
                </Button>
              </div>

              <div
                ref={conversationRef}
                className="flex-1 overflow-y-auto p-4 space-y-4 min-h-0"
              >
                {conversationItems.length === 0 ? (
                  <div className="text-center text-slate-500 py-8">
                    <MessageSquare className="w-12 h-12 mx-auto mb-3 text-slate-300" />
                    <p className="text-sm">No messages yet</p>
                    <p className="text-xs mt-1">
                      Start talking to see the conversation here
                    </p>
                  </div>
                ) : (
                  conversationItems.map((item, index) => (
                    <div
                      key={`${item.conversationId}-${index}`}
                      className={`flex ${item.sender === "user" ? "justify-end" : "justify-start"}`}
                    >
                      <div
                        className={`max-w-[80%] rounded-lg px-4 py-2 ${
                          item.sender === "user"
                            ? "bg-blue-500 text-white"
                            : "bg-slate-100 text-slate-900"
                        }`}
                      >
                        <p className="text-sm">{item.content.message}</p>
                        <div
                          className={`flex items-center gap-2 mt-1 text-xs ${
                            item.sender === "user"
                              ? "text-blue-100"
                              : "text-slate-500"
                          }`}
                        >
                          <span className="capitalize">{item.sender}</span>
                          {item.timestamp && (
                            <span>
                              {new Date(item.timestamp).toLocaleTimeString()}
                            </span>
                          )}
                        </div>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}
        </div>

        {/* Control Panel */}
        <div className="mt-6 bg-white rounded-xl shadow-lg border border-slate-200 p-6">
          <div className="flex items-center justify-between">
            {/* Media Controls */}
            <div className="flex items-center gap-3">
              <div className="flex items-center gap-2">
                <span className="text-sm font-medium text-slate-700">
                  Camera:
                </span>
                <Button
                  variant={isCameraOn ? "default" : "outline"}
                  size="sm"
                  onClick={toggleCamera}
                  disabled={!isConnected}
                  className="flex items-center gap-2"
                >
                  {isCameraOn ? (
                    <Video className="w-4 h-4" />
                  ) : (
                    <CameraOffIcon className="w-4 h-4" />
                  )}
                  {isCameraOn ? "On" : "Off"}
                </Button>
              </div>

              <div className="flex items-center gap-2">
                <span className="text-sm font-medium text-slate-700">
                  Microphone:
                </span>
                <Button
                  variant={isMicOn ? "default" : "outline"}
                  size="sm"
                  onClick={toggleMic}
                  disabled={!isConnected}
                  className="flex items-center gap-2"
                >
                  {isMicOn ? (
                    <Mic className="w-4 h-4" />
                  ) : (
                    <MicOff className="w-4 h-4" />
                  )}
                  {isMicOn ? "On" : "Off"}
                </Button>
              </div>
            </div>

            {/* Connection Button */}
            <Button
              onClick={() =>
                isConnected
                  ? endSession()
                  : startSession({
                      onConversationMessageCreated: (item: ConversationItem) => {
                        console.log("Conversation message created:", item);
                      },
                      onSessionConnected: () => {
                        console.log("Session connected");
                      },
                      onSessionEnd: () => {
                        console.log("Session ended");
                      },
                      onSessionStart: () => {
                        console.log("Session started");
                      },
                      onError: (error: Error) => {
                        console.log("Session error:", error);
                      },
                      onConnectionStateChange: (state: ConnectionState) => {
                        console.log("Connection state changed:", state);
                      },
                    })
              }
              variant={isConnected ? "destructive" : "default"}
              size="lg"
              className="px-8"
            >
              {buttonText()}
            </Button>
          </div>
        </div>
      </div>

      {/* Audio Stream */}
      <OrgaAudio stream={aiAudioStream} />
    </div>
  );
}

// packages/sdk-vue/examples/basic-usage/App.vue
<template>
  <div id="app">
    <header>
      <h1>Orga AI Vue Demo</h1>
      <p>Real-time multimodal AI that hears, sees, and speaks</p>
    </header>

    <main>
      <!-- Video Stream -->
      <div class="video-container">
        <h3>Your Video</h3>
        <OrgaVideo 
          :userVideoStream="userVideoStream" 
          @loadedmetadata="onVideoLoaded"
          class="video-stream"
        />
        <p v-if="!userVideoStream" class="placeholder">
          Camera will appear here when enabled
        </p>
      </div>

      <!-- Audio (hidden, plays AI responses) -->
      <OrgaAudio 
        :aiAudioStream="aiAudioStream" 
        @play="onAudioPlay"
        style="display: none;"
      />

      <!-- Controls -->
      <div class="controls">
        <button 
          @click="startSession" 
          :disabled="connectionState !== 'closed'"
          class="btn btn-primary"
        >
          {{ connectionState === 'closed' ? 'Start Session' : 'Session Active' }}
        </button>
        
        <button 
          @click="endSession" 
          :disabled="connectionState === 'closed'"
          class="btn btn-secondary"
        >
          End Session
        </button>
        
        <button 
          @click="toggleMic" 
          :disabled="connectionState !== 'connected'"
          class="btn"
          :class="{ 'btn-active': isMicOn }"
        >
          {{ isMicOn ? '🎤 Mute' : '🎤 Unmute' }}
        </button>
        
        <button 
          @click="toggleCamera" 
          :disabled="connectionState !== 'connected'"
          class="btn"
          :class="{ 'btn-active': isCameraOn }"
        >
          {{ isCameraOn ? '📹 Turn Off Camera' : '📹 Turn On Camera' }}
        </button>
      </div>

      <!-- Configuration -->
      <div class="config-section">
        <h3>Configuration</h3>
        <div class="config-grid">
          <div class="config-item">
            <label>Model:</label>
            <select :value="model" @change="setModel($event.target.value)">
              <option value="orga-1-beta">Orga 1 Beta</option>
              <option value="orga-1-pro">Orga 1 Pro</option>
            </select>
          </div>
          
          <div class="config-item">
            <label>Voice:</label>
            <select :value="voice" @change="setVoice($event.target.value)">
              <option value="alloy">Alloy</option>
              <option value="echo">Echo</option>
              <option value="fable">Fable</option>
              <option value="onyx">Onyx</option>
              <option value="nova">Nova</option>
              <option value="shimmer">Shimmer</option>
            </select>
          </div>
          
          <div class="config-item">
            <label>Temperature: {{ temperature }}</label>
            <input 
              type="range" 
              min="0" 
              max="2" 
              step="0.1" 
              :value="temperature" 
              @input="setTemperature(Number($event.target.value))"
              class="slider"
            />
          </div>
        </div>
      </div>

      <!-- Status -->
      <div class="status-section">
        <h3>Status</h3>
        <div class="status-grid">
          <div class="status-item">
            <strong>Connection:</strong> 
            <span :class="`status-${connectionState}`">{{ connectionState }}</span>
          </div>
          <div class="status-item" v-if="conversationId">
            <strong>Conversation ID:</strong> {{ conversationId }}
          </div>
          <div class="status-item">
            <strong>Messages:</strong> {{ conversationItems.length }}
          </div>
        </div>
      </div>

      <!-- Conversation -->
      <div class="conversation-section" v-if="conversationItems.length > 0">
        <h3>Conversation</h3>
        <div class="conversation">
          <div 
            v-for="(item, index) in conversationItems" 
            :key="index" 
            class="message"
            :class="`message-${item.sender}`"
          >
            <div class="message-header">
              <strong>{{ item.sender === 'user' ? 'You' : 'Orga AI' }}</strong>
              <span class="timestamp">{{ formatTime(item.timestamp) }}</span>
            </div>
            <div class="message-content">{{ item.content.message }}</div>
          </div>
        </div>
      </div>
    </main>

    <footer>
      <p>Built with Vue 3 and Orga AI SDK</p>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { useOrgaAI, OrgaAudio, OrgaVideo } from '@orga-ai/vue';
import { OrgaAI } from '@orga-ai/core';

// Initialize OrgaAI (in a real app, this would be in your main.ts or app setup)
OrgaAI.init({
  apiKey: 'your-api-key-here', // Replace with your actual API key
  fetchSessionConfig: async () => {
    // This is a placeholder - replace with your actual session config endpoint
    return {
      ephemeralToken: 'demo-token',
      iceServers: [
        { urls: 'stun:stun.l.google.com:19302' }
      ]
    };
  }
});

// Use the OrgaAI provider context
const {
  // Session management
  startSession,
  endSession,
  
  // Media controls
  toggleMic,
  toggleCamera,
  
  // State
  connectionState,
  userVideoStream,
  aiAudioStream,
  isMicOn,
  isCameraOn,
  conversationId,
  conversationItems,
  
  // Configuration
  model,
  voice,
  temperature,
  setModel,
  setVoice,
  setTemperature
} = useOrgaAI();

// Event handlers
const onVideoLoaded = () => {
  console.log('Video stream loaded and ready');
};

const onAudioPlay = () => {
  console.log('AI audio response is playing');
};

// Utility function to format timestamps
const formatTime = (timestamp?: string) => {
  if (!timestamp) return '';
  return new Date(timestamp).toLocaleTimeString();
};
</script>

<style scoped>
#app {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

header {
  text-align: center;
  margin-bottom: 30px;
}

header h1 {
  color: #333;
  margin-bottom: 10px;
}

header p {
  color: #666;
  font-size: 1.1em;
}

main {
  display: flex;
  flex-direction: column;
  gap: 30px;
}

.video-container {
  text-align: center;
}

.video-stream {
  width: 100%;
  max-width: 400px;
  height: 300px;
  border: 2px solid #ddd;
  border-radius: 8px;
  background: #f8f9fa;
}

.placeholder {
  color: #999;
  font-style: italic;
  margin-top: 10px;
}

.controls {
  display: flex;
  gap: 15px;
  justify-content: center;
  flex-wrap: wrap;
}

.btn {
  padding: 12px 20px;
  border: none;
  border-radius: 6px;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s ease;
}

.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.btn-primary {
  background: #007bff;
  color: white;
}

.btn-primary:hover:not(:disabled) {
  background: #0056b3;
}

.btn-secondary {
  background: #6c757d;
  color: white;
}

.btn-secondary:hover:not(:disabled) {
  background: #545b62;
}

.btn-active {
  background: #28a745 !important;
  color: white;
}

.config-section,
.status-section,
.conversation-section {
  background: #f8f9fa;
  padding: 20px;
  border-radius: 8px;
  border: 1px solid #e9ecef;
}

.config-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 20px;
  margin-top: 15px;
}

.config-item {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.config-item label {
  font-weight: 500;
  color: #333;
}

.config-item select,
.config-item input {
  padding: 8px 12px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 14px;
}

.slider {
  width: 100%;
}

.status-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 15px;
  margin-top: 15px;
}

.status-item {
  display: flex;
  flex-direction: column;
  gap: 5px;
}

.status-closed { color: #6c757d; }
.status-connecting { color: #ffc107; }
.status-connected { color: #28a745; }
.status-failed { color: #dc3545; }

.conversation {
  max-height: 400px;
  overflow-y: auto;
  margin-top: 15px;
}

.message {
  margin: 15px 0;
  padding: 15px;
  border-radius: 8px;
  border-left: 4px solid;
}

.message-user {
  background: #e3f2fd;
  border-left-color: #2196f3;
}

.message-assistant {
  background: #f3e5f5;
  border-left-color: #9c27b0;
}

.message-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
}

.timestamp {
  font-size: 0.85em;
  color: #666;
}

.message-content {
  line-height: 1.5;
}

footer {
  text-align: center;
  margin-top: 40px;
  padding-top: 20px;
  border-top: 1px solid #eee;
  color: #666;
}

@media (max-width: 768px) {
  #app {
    padding: 15px;
  }
  
  .controls {
    flex-direction: column;
    align-items: center;
  }
  
  .config-grid,
  .status-grid {
    grid-template-columns: 1fr;
  }
}
</style>
